In [1]:
import torch
import numpy as np
import pandas as pd

[Attention Is All You Need -- Figure 1: The Transformer](https://arxiv.org/pdf/1706.03762) ----- [图示详解](https://zhuanlan.zhihu.com/p/338817680)

Torch Example: https://github.com/Jiarong-L/BioDL/blob/main/1.%20Protein_seq_Classifier/VFDB_Transformer.ipynb  
1. PositionalEncoding
2. nn.TransformerEncoderLayer + nn.

## Transformer

$attention = softmax(\frac{QK'}{\sqrt{d_K}})V$

Multi Head Attention 就是将多个并行输出的 Attention 进行 weighted sum
```bash
MultiHead(Q, K, V) = Concat(head₁, head₂, ..., headₕ)Wᴼ

其中 headᵢ = Attention(QWᵢᴼ, KWᵢᴷ, VWᵢⱽ)
```

In [2]:
d_k = 6         ## output of transformer
word_emb = 5    ## d_model  or  d_token
seq_len = 4

WQ = np.random.rand(word_emb,d_k)
WK = np.random.rand(word_emb,d_k)    ## d_token -> d_output
WV = np.random.rand(word_emb,d_k)


input = pd.DataFrame({
    "<sos>": np.random.randn(word_emb),
    "<you>": np.random.randn(word_emb),
    "<like>": np.random.randn(word_emb),
    "<swimming>": np.random.randn(word_emb),
}).T


Q = input @ WQ    ## query [seq_len, d_k] = [seq_len, word_emb] @  [word_emb, d_k]
K = input @ WK    ##   key [seq_len, d_k]
V = input @ WV    ## value [seq_len, d_k]

def softmax(M):
    M = M.values
    M = M - np.max(M, axis=1, keepdims=True)
    return np.exp(M)/np.sum(np.exp(M),axis=1,keepdims=True)


Att = softmax(Q @ K.T /np.sqrt(d_k)) @ V
## Multi-head = np.concatenate(Att_1,Att_2,Att_3)WH    ##-->WH is each attention's weight

Att

          0         1         2         3         4         5
0 -0.172690 -0.486924 -0.278153 -0.491957 -0.584998 -0.058128
1  1.200625  0.828974  1.284056  1.739355  1.774761 -0.075486
2 -1.118485 -1.137167 -1.040982 -1.570663 -1.709073 -0.936248
3  0.472526  0.012790  0.341578  0.377390  0.327005  0.234591

In [3]:
## pytorch Function
## https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html

torch.nn.functional.scaled_dot_product_attention(torch.tensor(Q.values), torch.tensor(K.values), torch.tensor(V.values))

tensor([[-0.1727, -0.4869, -0.2782, -0.4920, -0.5850, -0.0581],
        [ 1.2006,  0.8290,  1.2841,  1.7394,  1.7748, -0.0755],
        [-1.1185, -1.1372, -1.0410, -1.5707, -1.7091, -0.9362],
        [ 0.4725,  0.0128,  0.3416,  0.3774,  0.3270,  0.2346]],
       dtype=torch.float64)

[图示详解](https://zhuanlan.zhihu.com/p/338817680)：Attention矩阵的每一行，对应一个单词的表示

Attention QKV 的意义是什么呢？

```bash
假设输入句子是 "A to B"

Q[A]：我在寻找与'A'相关的东西
K[A]：我是关于'A'的
V[A]：包含'A'的所有语义信息

QK[A,A] =  Q[A]·K[A]    'A'的自我关联
QK[A,to] = Q[A]·K[to]   'A'与'to'的关系
QK[A,B] =  Q[A]·K[A]    'A'与'B'的关系

（忽略softmax步骤）

QKV[A] = QK[A,A]·V[A] + QK[A,to]·V[to] + QK[A,B]·V[B]
       =  0.4×V[A] + 0.2×V[to] + 0.4×V[B]

上文的 token_embd 中也可以附上 **Positional Encoding** 信息，即将 Transformer 的输入变成 ```concat(token_emb, position_enc)```

$PE_{(pos,2i)} = sin(pos/10000^{2i/d_{tokenEmbd}})$   
$PE_{(pos,2i+1)} = cos(pos/10000^{2i/d_{tokenEmbd}})$  
$PE_{(others)} = 0$

其中，$pos$指token在句子中的定位，$i$指在token向量中的定位

**如果不加入pos**，Attention可能会无法区分：

In [4]:
input_1 = pd.DataFrame({
    "<A>":    [1,0,0],
    "<like>": [0,1,0],
    "<B>":    [0,0,1]
}).T

input_2 = pd.DataFrame({
    "<B>":    [0,0,1],
    "<like>": [0,1,0],
    "<A>":    [1,0,0]
}).T

WQ = np.random.rand(3,d_k)
WK = np.random.rand(3,d_k)  
WV = np.random.rand(3,d_k)

(Q1,K1,V1) = (input_1 @ WQ , input_1 @ WK, input_1 @ WV)
(Q2,K2,V2) = (input_1 @ WQ , input_1 @ WK, input_1 @ WV)


Att_1 = softmax(Q1 @ K1.T /np.sqrt(d_k)) @ V1
Att_2 = softmax(Q2 @ K2.T /np.sqrt(d_k)) @ V2

Att_1 == Att_2

      0     1     2     3     4     5
0  True  True  True  True  True  True
1  True  True  True  True  True  True
2  True  True  True  True  True  True

### Mask

```

Encoder:    (pos_emb,seq_source) ------------ [attention] ---------- [Forward] ---- (feature)

Decoder:    (feature,pos_emb,seq_target) ---- [masked_attention] --- [Forward] ---- (next word)


(feature,pos_emb,'<sos>') ---> Decoder ---> 'you'
(feature,pos_emb,'<sos> you') ---> Decoder ---> 'like'
(feature,pos_emb,'<sos> you like') ---> Decoder ---> 'swimming'
(feature,pos_emb,'<sos> you like swimming') ---> Decoder ---> '<eos>'
```

Decoder训练时已知晓生成的序列，可以一次计算它的attention矩阵；但输入时需要mask掉暂未使用的部分：Masked_QK * V 得到 Masked Self-Attention

In [5]:
QKt = Q @ K.T / np.sqrt(d_k)
QKt_tensor = torch.tensor(QKt.values)
QKt

               <sos>     <you>    <like>  <swimming>
<sos>      -0.061314 -0.510980  0.507694    0.163830
<you>       0.469564  3.227190 -4.105081   -1.348625
<like>     -0.436464 -1.817011  3.413680    0.929406
<swimming> -0.165879  0.674519 -0.309751    0.439472

In [6]:
mask = torch.tril(torch.ones_like(QKt_tensor))
mask == 0

tensor([[False,  True,  True,  True],
        [False, False,  True,  True],
        [False, False, False,  True],
        [False, False, False, False]])

In [7]:
QKt_att = QKt_tensor.masked_fill_(mask == 0,-torch.inf)
QKt_att

tensor([[-0.0613,    -inf,    -inf,    -inf],
        [ 0.4696,  3.2272,    -inf,    -inf],
        [-0.4365, -1.8170,  3.4137,    -inf],
        [-0.1659,  0.6745, -0.3098,  0.4395]], dtype=torch.float64)

In [8]:
torch.softmax(QKt_att, dim=-1)

tensor([[1.0000, 0.0000, 0.0000, 0.0000],
        [0.0597, 0.9403, 0.0000, 0.0000],
        [0.0207, 0.0052, 0.9741, 0.0000],
        [0.1662, 0.3852, 0.1440, 0.3045]], dtype=torch.float64)